// user.h
#ifndef USER_H
#define USER_H

#include <string>
#include <ctime>
#include <iostream>
#include <vector>
#include "utils.h" // Bao gom cac ham tien ich

class User {
public:
    // Thuoc tinh co ban cua nguoi dung
    std::string username;          // Ten dang nhap (duy nhat)
    std::string hashedPassword;    // Mat khau da bam
    std::string fullName;
    std::string email;
    std::string phoneNumber;
    std::string userId;            // ID duy nhat cho nguoi dung
    time_t registrationDate;       // Thoi gian dang ky

    // Thuoc tinh quan ly mat khau
    bool isAutoGeneratedPassword;  // true neu mat khau duoc tu dong sinh

    // Thuoc tinh phan quyen
    std::string userType;          // "normal" hoac "admin"

    // Constructor
    User(std::string username, std::string hashedPassword, std::string fullName,
         std::string email, std::string phoneNumber, std::string userType,
         bool isAutoGenerated = false);

    // Cac ham thanh vien (methods)
    void displayUserInfo() const;

    // Cac ham cap nhat thong tin ca nhan
    void updateFullName(const std::string& newFullName);
    void updateEmail(const std::string& newEmail);
    void updatePhoneNumber(const std::string& newPhoneNumber);
    void changePassword(const std::string& newHashedPassword);

    // Getters de truy cap cac thuoc tinh
    std::string getUsername() const { return username; }
    std::string getHashedPassword() const { return hashedPassword; }
    std::string getFullName() const { return fullName; }
    std::string getEmail() const { return email; }
    std::string getPhoneNumber() const { return phoneNumber; }
    std::string getUserId() const { return userId; }
    std::string getUserType() const { return userType; }
    bool getIsAutoGeneratedPassword() const { return isAutoGeneratedPassword; }

    // Phuong thuc de chuyen doi doi tuong User thanh chuoi de luu vao file
    std::string toString() const;

    // Phuong thuc tinh de tao doi tuong User tu chuoi doc tu file
    static User* fromString(const std::string& data);

    // Phuong thuc de luu doi tuong User vao file
    // (Code trong .cpp se them cap nhat file index)
    bool saveToFile() const;

    // Phuong thuc tinh de tai doi tuong User tu file dua tren username
    static User* loadFromFile(const std::string& username);
};

#endif // USER_H

